### ISSUE TITLE
Add tests with 'overflow: auto' elements in a scrolled document

### ISSUE THREAD

**Issue by notriddle** [servo/servo#11019]
[![The stuff in the `<pre><code>` section on GitHub is invisible](http://i.imgur.com/m73C7x4.png)](http://imgur.com/m73C7x4)

Note that the mouse cursor does not respond to the text that should be underneath it, either.

**Comment by notriddle** [comment]
(assigned A-browserhtml/P2 because it affects GitHub in a pretty severe way; feel free to remove the prioritization if it's wrong)

**Comment by Manishearth** [comment]
```rust
let this = is(a.code.block);
fn this(is: A) {
 // function
}
```

**Comment by SimonSapin** [comment]
I’m looking into this.

**Comment by SimonSapin** [comment]
I’ve isolated the bug: content inside an element with `overflow: auto` (like code blocks on GitHub) does not scroll on WebRender. If a code block is initially outside the viewport it is invisible. Scrolling the page to make it come into view doesn’t move the content, which then stays invisible.

Test case (scroll this when running with `-w`):

```html
<div style="overflow: auto">overflow: auto</div>

Extra content to make the viewport scroll:

<p style="height: 100px">1
<p style="height: 100px">2
<p style="height: 100px">3
<p style="height: 100px">4
<p style="height: 100px">5

**Comment by SimonSapin** [comment]
CC @pcwalton @glennw

**Comment by SimonSapin** [comment]
This also happens with iframes. I suspect with anything that creates a `Layer` in WebRender. https://github.com/servo/webrender/issues/283

**Comment by SimonSapin** [comment]
This seems fixed now, possibly by https://github.com/servo/webrender/pull/282.

Leaving this open since we don’t have any regression test yet. A reftest could use script code like `document.documentElement.scrollTop = 100` to simulate scrolling.

**Comment by ConnorGBrewster** [comment]
This issue does not seem to be fixed (or it has regressed since servo/webrender#282).

**Comment by ConnorGBrewster** [comment]
The preview test case seems to work now, here is a new test case that does not:
```
<p style="height: 500px">1
<p style="height: 500px">2
<div style="overflow: auto;">overflow: auto</div>
<p style="height: 500px">3
```
If the `overflow: auto;` div is initially positioned outside the viewport, when you scroll down the text is not there. If the div is initially positioned inside the viewport, the text renders in the correct position even after scrolling.

**Comment by notriddle** [comment]
It's still present in WR2.

![screenshot from 2016-08-03 09-24-17](https://cloud.githubusercontent.com/assets/1593513/17373224/1dc2eb3c-595c-11e6-87f7-33d5aa1d67b4.png)

**Comment by mrobinson** [comment]
Pretty sure this isn't an issue any longer, so I'm going to close this one. If you still see it, feel free to reopen the bug.

**Comment by SimonSapin** [comment]
(Or comment, @-mentioning someone to ask to reopen, since if I remember correctly only people with write access to the repository can reopen closed issues.)

**Comment by mrobinson** [comment]
@SimonSapin Oh! That's good to know. Yes Just @ me and I'll be happy to reopen this one.
