### ISSUE TITLE
Layout constantly redone on cnn.com

### ISSUE THREAD

**Issue by jarretraim** [servo/servo#12055]
Downloaded and installed servo nightly today (2016-07-01) on OSX 10.11.5. Went to cnn.com

Servo loads for several seconds, then begins to display parts of the CNN page. The loading bar is still visible and the site continues to load very slowly and the CPU spikes (see screenshot). 

![screenshot 2016-07-01 08 37 33](https://cloud.githubusercontent.com/assets/981154/16523169/90cafdf4-3f67-11e6-9d96-33423a941ace.png)

After ~30 seconds or so of high CPU usage (CNN site still isn't loaded) Servo crashed with the following crash report.

[Crash Report](https://dl.dropboxusercontent.com/u/2592712/servo-crash.txt)

**Comment by jdm** [comment]
I haven't been able to reproduce this in a local debug build yet.

**Comment by jarretraim** [comment]
Checked it just now to ensure it wasn't some add thing and it still seems in force, but it might already be fixed in the debug build. Happy to test with it when it is released or if there is a way to download it now.

**Comment by sviter** [comment]
Can't reproduce this also on Win10

**Comment by nox** [comment]
Servo doesn't crash anymore, but high CPU usage is still here. The flag `show-parallel-layout` shows that there the page's layout is constantly redone, which may be why the CPU is going crazy.

**Comment by lumiscosity** [comment]
Still happens. Tested on Arch Linux x86_64, Servo built against commit 633d746e2f1f0bb397e884381bbb7fab89284006, profiling build.

<img width="2314" height="1058" alt="Image" src="https://github.com/user-attachments/assets/b5f2256e-6f6f-4e49-b752-574873343f13" />

**Comment by lumiscosity** [comment]
Now seems to be fixed. The page remains responsive after fully loading, continues to run fine after resizing the window and doesn't use large amounts of CPU. Tested on Arch Linux x86_64, Servo built against 545faa2337dc0272105351a4d48ba1f27198cf61, dev and release builds.

<img width="1779" height="821" alt="Image" src="https://github.com/user-attachments/assets/8a5e4d2e-0684-4787-8822-1ff3c8c8e144" />
