### ISSUE TITLE
`<input type=radio>` marker isn't aligned properly

### ISSUE THREAD

**Issue by simonwuelker** [servo/servo#34969]
```html
<body>
<fieldset>
  <legend>Select a maintenance drone:</legend>

  <div>
    <input type="radio" id="huey" name="drone" value="huey" checked />
    <label for="huey">Huey</label>
  </div>

  <div>
    <input type="radio" id="dewey" name="drone" value="dewey" />
    <label for="dewey">Dewey</label>
  </div>

  <div>
    <input type="radio" id="louie" name="drone" value="louie" />
    <label for="louie">Louie</label>
  </div>
</fieldset>
```

![image](https://github.com/user-attachments/assets/c4cf6ba3-eb4d-460c-bd91-5f3e569d268b)

I would expect the marker to be centered within the outer circle, instead of at the bottom.

**Comment by DevGev** [comment]
Can this be fixed by updating `resources/servo.css`, since running the same styles from Servo under Firefox/Chromium also leads to _similar_ visual artifacts?

```html
<style>
.myradio[type="radio"] {
  font-family: monospace !important;
  border: none !important;
  background: transparent;
}

.myradio[type="radio"]::before {
  display: inline-block;
  border: solid currentcolor 1px;
  content: "";
  padding: 0;
  width: 1em;
  height: 1em;
  border-radius: 50%;
  text-align: center;
}

.myradio[type="radio"]::before { content: "●"; line-height: 1em; }
</style>

<div class="myradio" type="radio" id="huey" name="drone" value="huey" checked ></div>

```

The same radio button styles under Firefox and Chromium (not completely vertically centered): <br>
![Image](https://github.com/user-attachments/assets/286c9ed3-f593-46bc-bb6a-6b2b3f323996)

Changing `line-height: 1em;`  to eg. `line-height: 0.60rem;` aligns the circle better to the middle in Servo, Firefox, and Chromium for me.

Are the styles in `resources/servo.css` standardized or part of a specification, or can they be changed? Obviously there are some rendering issues so it might only be a _dirty fix_, however the styles seem off anyways.

**Comment by simonwuelker** [comment]
I believe these styles are just stubs anyways (I don't think authors should be able to override `.myradio[type="radio"]::before : content` for example). So fixing them is fine, but ultimately we will want to look for a better solution, like moving the implementation of radio inputs into a shadow tree.

**Comment by mrobinson** [comment]
This looks better in macOS. @simonwuelker are you still seeing this issue?

**Comment by lukewarlow** [comment]
It's better but still not quite perfect for me on macOS 26.2

<img width="240" height="104" alt="Image" src="https://github.com/user-attachments/assets/536b4222-58c8-4816-bb43-e8ca4201b35f" />
