### ISSUE TITLE
SecurityError when calling history.replaceState() in a file:/// context

### ISSUE THREAD

**Issue by delan** [servo/servo#35827]
To reproduce, save the following as test.html and open in Servo:

```html
<script>history.replaceState(null,null,"?")</script>
```

I would expect this to change the location to `file:///path/to/test.html?` but it instead throws:

```
[2025-03-07T01:54:41Z ERROR script::dom::bindings::error] Error at :0:0 SecurityError: The operation is insecure.
```

**Comment by jdm** [comment]
Step 2 of https://html.spec.whatwg.org/multipage/nav-history-apis.html#shared-history-push/replace-state-steps says to throw this exception if the document is not fully active. When we implemented replaceState the spec's definition of fully active was quite different than it is now, which changed in https://github.com/whatwg/html/pull/6315.

**Comment by jdm** [comment]
This occurs because of https://github.com/servo/servo/blob/1864ebfb357cdf4ac6f97d53c5f74f989f08b2ec/components/script/dom/history.rs#L227-L230 . However it appears the spec does not include an origin comparison in https://html.spec.whatwg.org/multipage/nav-history-apis.html#can-have-its-url-rewritten any more, so we should update our implementation.

**Comment by jdm** [comment]
We should add a new helper method that implements the steps of https://html.spec.whatwg.org/multipage/nav-history-apis.html#can-have-its-url-rewritten and replace the parts of https://html.spec.whatwg.org/multipage/nav-history-apis.html#shared-history-push/replace-state-steps that are now out of date. This will all happen in the history.rs file I linked in my previous comment.

Besides the manual testcase from the original comment, you can run `./mach test-wpt tests/html/browsers/history/the-history-interface` and see if there are any unexpected results.

**Comment by kkoyung** [comment]
The PR #35864 currently fixes the error message, but the address bar still doesn't show the updated url yet.

**Comment by atouchet** [comment]
Should this be re-opened then?

**Comment by jdm** [comment]
I think a separate issue should be opened for any problems with the location bar or title not updating.
