### ISSUE TITLE
`about:memory` page crashes when clicking "Measure"

### ISSUE THREAD

**Issue by yezhizhen** [servo/servo#37238]
**Describe the bug:**
After clicking "Measure", it hangs for a second and then crash.
![Image](https://github.com/user-attachments/assets/aa2aa7e5-087e-487d-9333-a76f3926cbeb)

Setting `RUST_LOG` to either "info" or "error" shows nothing.

**To Reproduce:**
Load "about:memory", click measure

**Platform:**
Windows. Not sure if other platform also crashes.

**Comment by mrobinson** [comment]
@yezhizhen Does it produce a stack trace or an escape code?

**Comment by simonwuelker** [comment]
I can't reproduce this on linux.

**Comment by d-desiatkin** [comment]
In my understanding that likely happens cause servo uses jemalloc on most platforms, and this library have convenient methods to report memory usage. But on windows we use system allocator and it doesn't have convenient methods to report memory usage (It is quite probable that this page have never worked propperly on windows). Also there is PR that proposes mimalloc addition for windows. Mimalloc have some API for memory reporting, but it is not as convenient as jemalloc one

#37225 

Important notice! I haven't check that part in servo code. Comment above is based on my previous experience with this libraries

**Comment by yezhizhen** [comment]
> [@yezhizhen](https://github.com/yezhizhen) Does it produce a stack trace or an escape code?

No. Literally nothing is shown.

> Mimalloc have some API for memory reporting
> 
> [#37225](https://github.com/servo/servo/pull/37225)

I tried both Mimalloc and system allocator. Both would crash without any info or stack trace.

**Comment by mrobinson** [comment]
> > [@yezhizhen](https://github.com/yezhizhen) Does it produce a stack trace or an escape code?
> 
> No. Literally nothing is shown.


Can you try running in a debugger like `gdb` to see if you can capture a backtrace?

**Comment by sebsebmc** [comment]
I grabbed the Windows nightly from 2025-03-08 which should be the first one with the `about:memory` page and it crashes when clicking measure. I attached Windbg to the process and clicking on measure gave me this stack 

![Image](https://github.com/user-attachments/assets/8cebc8d1-ab86-4ada-80b8-a2523c8db647)

This does seem to validate the theory that this page was always broken on Windows.

**Comment by webbeef** [comment]
Does that also crash with earlier builds where the memory info was dumped to the console when using the `-m 5` flag?

**Comment by sebsebmc** [comment]
Nightly from 2025-03-07 launched with `-m 5` results in the same error code and stack trace output in Windbg. This did also indicate it was the script thread (1,1) was the one that faulted.

**Comment by mxmgorin** [comment]
This could be the cause: on Windows, the `mallocSizeOf` hook is `_msize`, and it is called with a null pointer, which aborts the process. This was encountered as CI failure in the new test for #48016, which takes a memory report.

servo/mozjs#816 should fix it; worth re-testing here once it merged and mozjs is bumped.

**Comment by jdm** [comment]
@yezhizhen Would you mind retesting?

**Comment by yezhizhen** [comment]
It depends. It still crashes after you load about:memory starting from some websites, such as https://jooyouss.github.io/candy-crush/ and measure.

But the original problem is fixed.

**Comment by jdm** [comment]
If you could catch that in windbg and share a backtrace, I would be interested in that!
