### ISSUE TITLE
<svg width> fails to scale contents to inferred height

### ISSUE THREAD

**Issue by delan** [servo/servo#41273]
Servo 0.0.3 renders this differently to Firefox:

`data:text/html,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10" width="300"><circle id="myCircle" cx="5" cy="5" r="4"/>`

| Servo | Firefox |
|---|---|
| <img width="332" height="258" alt="Image" src="https://github.com/user-attachments/assets/d5fc9c77-d1f5-458c-9868-d6133a52a482" /> | <img width="320" height="320" alt="Image" src="https://github.com/user-attachments/assets/49565152-aded-48f7-8178-63e58b4e2efd" /> |

it’s unclear to me whether the correct behaviour is specified anywhere.

**Comment by delan** [comment]
this shows that Servo is inferring height as expected, but failing to scale the contents:

`data:text/html,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10" width="300" style="border: 1px solid;"><circle id="myCircle" cx="5" cy="5" r="4"/>`

<img width="322" height="400" alt="Image" src="https://github.com/user-attachments/assets/f17f9bd6-72cc-447d-9530-41dab020027e" />

**Comment by simartin** [comment]
FWIW, it seems to be happening only if only one of `height` and `width` is specified; when both are, scaling seems to be happening

This is with `data:text/html,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10" width="300" height="300" style="border: 1px solid;"><circle id="myCircle" cx="5" cy="5" r="4.8"/>`

<img width="380" height="411" alt="Image" src="https://github.com/user-attachments/assets/8b7ba8bd-a803-4bd7-beea-bbbaa2cffb89" />

**Comment by simartin** [comment]
@servo-highfive assign me

**Comment by servo-highfive** [comment]
Hey @simartin! Thanks for your interest in working on this issue. It's now assigned to you!

**Comment by delan** [comment]
@Loirooriol was this fixed by #42577 (#42573)?

**Comment by delan** [comment]
ahh, i think they are actually unrelated, never mind. height vs width, and SVG contents vs replaced box.

**Comment by delan** [comment]
still affects the latest nightly ([2026-03-17](https://github.com/servo/servo-nightly-builds/releases/tag/2026-03-17)):

<img width="365" height="392" alt="Image" src="https://github.com/user-attachments/assets/cf266c2b-eb5e-4812-ae12-ab5a6f9ee9ea" />

**Comment by Loirooriol** [comment]
The replaced box is sized correctly. But the image inside is sized by resvg, which doesn't use viewbox correctly. A while ago I took a quick look and I couldn't improve the behavior without breaking lots of other cases.

**Comment by simartin** [comment]
Short update just for the record, knowing I'd never read about SVG until this week, so am likely to misinterpret a lot of things:
- I'm still not clear whether what we're showing is right or not: it seems from my reading that not specifying a height means take 100% of the viewbox' height, which could explain what we're seeing. It the same time, it sounds pretty natural to do some scaling, so 🤷‍♂️
- We have a [ TODO](https://github.com/servo/servo/blob/dc9e442b179f0be29a3a7afec337538a6b78ef54/components/layout/replaced.rs#L575) that seems relevant :-)
- It's fun, so I plan to keep looking

**Comment by lumiscosity** [comment]
That TODO is now gone, and the second test case now looks like this:

<img width="320" height="319" alt="Image" src="https://github.com/user-attachments/assets/72d566b5-19a8-4766-80f0-201930fcd77a" />

The height got scaled, but the width didn't get scaled accordingly unlike in Firefox.

I'm playing around with a few tests where the test itself is successful but the ref is failing where I'm observing a similar issue:
https://github.com/web-platform-tests/wpt/blob/b3bff5b802b7c8ea0f72238cb1cdcd6014edeb0e/css/css-transforms/scale/reference/svg-scale-ref.html

The new (or rather remaining?) issue seems to be in how the _explicit_ percentage based scaling gets the enviroment. 100% is a 100px square, 200% is a 200px square, but setting `background: green` in the `svg {...}` like there is on the tests shows that the space taken up by the element is indeed 200px. In our circle test case, the width scaling fails because it's explicitly set to 300, but the height isn't.

**Comment by simartin** [comment]
> That TODO is now gone, and the second test case now looks like this:

Indeed, https://github.com/servo/servo/pull/44420 is making things much better now.

**Comment by simartin** [comment]
We give the SVG document to [resvg](https://github.com/linebender/resvg) that determines that the size is 10x300, and everything we see comes from this.

This [slide deck](https://docs.google.com/presentation/d/1POUiroOBbLmXYlQKf0pIR8zVkHWH9jRVN-w8A4aNsIk/edit?) shows that not everybody agrees on what should happen in such cases.

I am working on a [patch](https://github.com/linebender/resvg/compare/main...simartin:only_one_width_height) to [resvg](https://github.com/linebender/resvg) implementing "the Firefox way", which makes sense to me, but I'm not super confident it will get approved especially if the standard does not give a definite answer on what to do in such cases.

We will see where it gets... (I hope it gets approved because the alternative is for us to patch the SVG XML document before giving it to [resvg](https://github.com/linebender/resvg), and I don't really want to do that ;-))

**Comment by simartin** [comment]
It looks pretty good with resvg patched locally (top is Servo, middle Firefox and bottom Chrome), so I'll go submit this patch 🤞 

<img width="958" height="1043" alt="Image" src="https://github.com/user-attachments/assets/44afeff7-0731-4944-9c94-7a56ad17b413" />

**Comment by simartin** [comment]
Funnily enough, my patch looks a lot like https://github.com/linebender/resvg/pull/715, that seems to have disappeared since 🙃 Will figure out what happned and update here...

EDIT: The code is still there, we just need it in some other place. Which increases the likelihood the patch is accepted.

**Comment by simartin** [comment]
This will be unfortunately blocked on a resvg upgrade, itself blocked on the minimum support rust version (see https://github.com/servo/servo/pull/43204#issuecomment-4045064554)

**Comment by TimvdLippe** [comment]
Resvg has now been updated

**Comment by simartin** [comment]
https://github.com/linebender/resvg/pull/1045 has been merged today so this ticket will be fixed when the resvg folks do their next release and we integrate it.

**Comment by atouchet** [comment]
<img width="512" height="317" alt="Image" src="https://github.com/user-attachments/assets/14cdbfbf-04ca-4b4a-95ac-b858531446ff" />

I think this is fixed now with the resvg update in #46937.

**Comment by simartin** [comment]
Yes indeed, this is fixed now 🎉

The ticket can be closed (I don't have the permissions to do it myself...)
