### ISSUE TITLE
Pass the WebSockets test suite.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#6060]
Tests are under `tests/wpt/web-platform-tests/websockets`, and expected failures are under `tests/wpt/metadata/websockets/`. See `tests/wpt/README.md` for more information on web platform tests.

**Comment by Chandler** [comment]
@jdm What's the best way to get started finding more websockets tests to fix. Should I just look for anything with "expected: FAIL" under tests/wpt/web-platform-tests/websockets ? 

All the existing websockets tickets are already being worked on https://github.com/servo/servo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+websockets

**Comment by KiChjang** [comment]
@Chandler Yes, we don't necessarily have issues for every failing test, so it's perfectly ok for you to submit a PR and fix them!

**Comment by jsanders** [comment]
@Chandler: FYI, a dump of all the current failures (not including what you fixed in #9367): https://gist.github.com/jsanders/4a348d15aa27067d2b02

**Comment by nox** [comment]
There is still a ton of failing tests, notably since we disabled support of `wss`.

**Comment by TimvdLippe** [comment]
Most test failures are variants that pass `?wpt_flags=h2 ` to the test. All other variants pass. Therefore, could it be related to HTTP2 integration with websockets? Cc @pylbrecht

**Comment by pylbrecht** [comment]
> Therefore, could it be related to HTTP2 integration with websockets?

The current spike integrating websockets into fetch (aa6166080037b90de44432b9d0bd08c224f43c1c) does not pass any tests from `/tests/wpt/tests/websockets/`. So, either the spike is still missing crucial pieces, or these failures are not related to websocket fetch integration.

**Comment by jdm** [comment]
I believe the http2 issues come from httparse only supporting http1 (https://docs.rs/httparse/latest/httparse/) and tungstenite relies on httparse. https://github.com/snapview/tungstenite-rs/issues/206
