### ISSUE TITLE
overflow:hidden changes the stacking order

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#8122]
```html
<style>

  div {
    width: 100px;
    height: 100px;
  }

  #a {
    background: red;
    position: absolute;
    top: 10px;
    left: 10px;
    overflow: hidden;
  }

  #b {
    background: blue;
    position: absolute;
    top: 20px;
    left: 20px;
  }
</style>

<body>
  <div id='a'></div>
  <div id='b'></div>
</body>
```

<img width="562" alt="screen shot 2015-10-21 at 11 58 11" src="https://cloud.githubusercontent.com/assets/373579/10633466/1cd76bce-77eb-11e5-99a7-ff93c1ad72bc.png">

**Comment by gilles-leblanc** [comment]
If this one is free for the taking I would like to have a look into it.

**Comment by jdm** [comment]
Sure looks like it!

**Comment by gilles-leblanc** [comment]
For the moment I'm stuck with this one. 

I have established that it works with overflow auto, scroll and visible. 

I have looked in ```components/gfx/display_list```. 

There's two files in this directory. One of them is the optimizer. 

I have taken out the optimizer (I've had it return the same ```display_list``` it was given in input as it's output) and the problem is still present, so that rules out an optimizer bug. 

I then looked at the ```mod.rs file```. I then also looked at ```components/layout/[block, display_list_builder].rs```. I don't understand everything going on in all those files yet though. Display lists, fragments, stacking order and even block elements are all pretty new to me so that makes a lot to absorb.

I've search ```components/gfx``` and ```components/layout``` for mentions of the terms ```overflow```, ```hidden``` and absolute positioning and looked at that code and made some changes to see if they had any impact. 

Do you have any suggestions as to where I could look next or any ideas?

I'm hoping for some angle on how to tackle this next.

**Comment by eefriedman** [comment]
CC @mrobinson

**Comment by metajack** [comment]
cc @pcwalton @glennw 

This is blocking browser.html work.

**Comment by mrobinson** [comment]
I believe this is also fixed by https://github.com/servo/servo/pull/8266.

**Comment by gilles-leblanc** [comment]
@mrobinson I have made a wpt test with the case written by @paulrouget which I have committed to a branch (https://github.com/gilles-leblanc/servo/commit/b2ba72a364a6439668f23a39d9623ae1b00f841a). I then pulled and merged your branch https://github.com/servo/servo/compare/master...mrobinson:stacking-context-mix and tested it but I'm still getting a failure on the test case.

**Comment by mrobinson** [comment]
@gilles-leblanc I ran your test locally on top of https://github.com/servo/servo/compare/master...mrobinson:stacking-context-mix and it seems to pass for me. Can you double-check by pulling the branch at https://github.com/mrobinson/servo/tree/gilles-test and testing again? If it continues to fail for you, would you post or describe the image diff from the test results analyzer at http://hoppipolla.co.uk/410/reftest-analyser-structured.xhtml?

**Comment by gilles-leblanc** [comment]
@mrobinson I pulled the branch and it's still failing but it's probably something on my side, some sort of mistake I did. I've created a gist with the log file: https://gist.github.com/gilles-leblanc/8e6467040d342272a996 which you can paste in the reftest analyser.

**Comment by mrobinson** [comment]
@gilles-leblanc Tests that were added for issues in previous PRs that I have landed seem to be failing as well. Can you double-check that you are not running the tests with a stale build? One thing that I sometimes do is to only compile a debug build and accidentally run the tests with --release flag or the opposite.

**Comment by gilles-leblanc** [comment]
@mrobinson Oh my bad I thought that the tests were ran with the last build, in my case a release build so I didn't supply the --release switch for the test command. 

Sorry! 

Everything now works.
