### ISSUE TITLE
Accept a sequence of strings in the WebSocket constructor

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9053]
The WebIDL definitions for WebSocket has been updated upstream at the HTML specification documentation. In our current code, we use `optional (DOMString or DOMString) protocols` as the second argument to the constructor of WebSockets. The updated spech [here](https://html.spec.whatwg.org/multipage/comms.html#the-websocket-interface) instead uses `optional (DOMString and sequence<DOMString>) protocols`.

Code: `components/script/dom/webidls/WebSockets.webidl`, `components/script/dom/websocket.rs`
Spec: https://html.spec.whatwg.org/multipage/comms.html#the-websocket-interface
Test: `tests/wpt/web-platform-tests/websockets/constructor.html`

**Comment by ecoal95** [comment]
I think this is blocked by #544

**Comment by KiChjang** [comment]
That issue is still open? Weird, because #9049 uses `sequence<>` for getAll and it compiled fine for me.

**Comment by KiChjang** [comment]
Oh I see what the problem is - `Codegen.py` currently doesn't support `sequence` values as parameters.

**Comment by ecoal95** [comment]
Yeah, I implemented return values in #8412, but no arguments yet.

**Comment by nox** [comment]
Blocked by #9056.

**Comment by frewsxcv** [comment]
#9056 has merged

**Comment by ckimes89** [comment]
Looks like this still won't work with the WebIDL definition since the second parameter is `optional (DOMString or sequence<DOMString>) protocols` and the codegen doesn't currently support sequences in union types.

https://github.com/servo/servo/blob/master/components/script/dom/bindings/codegen/CodegenRust.py#L3575

**Comment by frewsxcv** [comment]
Blocked on https://github.com/servo/servo/issues/9290 maybe?

**Comment by ecoal95** [comment]
@frewsxcv not really, that's not what that issue talks about.

#9290 is about the way we generate rust vectors from js values in `rust-mozjs`.

I should be studying but... I'm giving it a try.

**Comment by frewsxcv** [comment]
@ecoal95 studying should come first :)  At the very least, if you could, you could hastily open an issue describing the issue since #9290 is something different

**Comment by ecoal95** [comment]
@frewsxcv Too late! #9304

**Comment by ecoal95** [comment]
(actually I had it half written when I pressed the *comment* button :P)

**Comment by ecoal95** [comment]
This should be no longer blocked

**Comment by jsanders** [comment]
Just came across this while updating test expectations for my work on #7860, which fixes some stuff that was hiding failures caused by this issue. Can I grab this one as well, since I have spec'd out some changes for it in order to fix my test?

**Comment by nox** [comment]
@jsanders Sure!

**Comment by ckimes89** [comment]
@jsanders If you've already written/writing code for this then go for it, but I've got a commit ready that was waiting for #9304 to merge. In hindsight, I should have asked for this to be assigned.

**Comment by jsanders** [comment]
@ckimes89: D'oh, just pushed #9360. Looks like a pretty similar solution. I'm not fussed either way.

**Comment by ckimes89** [comment]
@jsanders All yours, I should've spoken up earlier.
